language: node_js
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database customers_test;' -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'root';" -U postgres
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
  - npm install -g codecov
script:
  - NODE_ENV=TEST nyc --reporter=lcovonly ./node_modules/.bin/mocha --recursive
  - codecov
